import {test,expect} from '@playwright/test';
const clinic='42000000-0000-0000-0000-000000000001';
const user='41000000-0000-0000-0000-000000000001';
const room='43000000-0000-0000-0000-000000000001';
const queue='44000000-0000-0000-0000-000000000001';
const patient='45000000-0000-0000-0000-000000000001';
const ticket='46000000-0000-0000-0000-000000000001';
const token='a'.repeat(64);
// Browser fixtures are explicitly test data. No requests write to a real Supabase project.
function workspace(role){return {role,clinic:{id:clinic,name:'TEST Clinic',timezone:'America/Sao_Paulo',city:'TEST City',contact_email:'clinic@example.test'},specialties:[{id:'47000000-0000-0000-0000-000000000001',name:'TEST Specialty'}],rooms:[{id:room,name:'TEST Room'}],queues:[{id:queue,name:'TEST Queue',status:'open',room_id:room,room_name:'TEST Room',doctor_name:'TEST Doctor',specialty_name:'TEST Specialty',expected_minutes:15}],patients:[{id:patient,name:'TEST Patient',user_id:null}],tickets:role==='patient'?[{id:ticket,number:1,status:'waiting',position:1,estimated_minutes:15,clinic:'TEST Clinic',queue:'TEST Queue'}]:[{id:ticket,number:1,status:'waiting',priority:false,patient_name:'TEST Patient',queue_id:queue,queue_name:'TEST Queue',room:null,created_at:new Date().toISOString()}],members:[{user_id:user,role:'doctor',name:'TEST Doctor',active:true}],invites:[],report:{total:1,completed:0,cancelled:0,absent:0,average_wait_minutes:null,average_service_minutes:null}};}
async function setup(page,role,{authenticated=true}={}){
 const state=workspace(role);if(role==='patient'){delete state.clinic;delete state.patients;}const operations=[];const errors=[];page.on('pageerror',e=>errors.push(e.message));
 if(authenticated)await page.addInitScript(()=>sessionStorage.setItem('medflow.session',JSON.stringify({access_token:'fixture-token-not-real',refresh_token:'fixture-refresh',expires_at:Math.floor(Date.now()/1000)+3600})));
 await page.route('**/auth/v1/**',route=>route.fulfill({json:{access_token:'fixture-token-not-real',refresh_token:'fixture-refresh',expires_in:3600},headers:{'Access-Control-Allow-Origin':'*'}}));
 await page.route('**/api/**',async route=>{
  const req=route.request();const path=new URL(req.url()).pathname;let result;
  if(path==='/api/me')result={id:user,email:'staff@example.test',platform_admin:false,memberships:[{clinic_id:clinic,role,clinics:{name:'TEST Clinic',status:'active'}}]};
  else if(path.endsWith('/workspace'))result=state;
  else if(path.endsWith('/actions')){
   const body=req.postDataJSON();operations.push(body);result={id:ticket};
   if(body.action==='checkin'){result={id:ticket,number:2,token};state.tickets.push({...state.tickets[0],id:'48000000-0000-0000-0000-000000000001',number:2});}
   if(body.action==='call')state.tickets[0].status='called';
   if(body.action==='start')state.tickets[0].status='in_service';
   if(body.action==='finish')state.tickets[0].status='completed';
   if(body.action==='invite')result={id:ticket,token};
  }else if(path==='/api/public/track')result={id:ticket,number:2,status:'called',room:'TEST Room',clinic:'TEST Clinic',queue:'TEST Queue',position:0,estimated_minutes:0};
  else if(path==='/api/invites/accept')result=clinic;
  else result=[];
  await route.fulfill({json:{data:result},headers:{'Access-Control-Allow-Origin':'*'}});
 });return {state,operations,errors};
}
test('login routes receptionist to the operational area',async({page})=>{const {errors}=await setup(page,'receptionist',{authenticated:false});await page.goto('/login.html');await page.getByLabel('E-mail',{exact:true}).fill('staff@example.test');await page.getByLabel('Senha',{exact:true}).fill('test-password-at-least-12');await page.getByRole('button',{name:'Entrar',exact:true}).click();await expect(page).toHaveURL(/recepcao\/index.html/);await expect(page.getByRole('heading',{name:'TEST Clinic'})).toBeVisible();expect(errors).toEqual([]);});
test('reception issues a ticket and provides a private tracking link',async({page})=>{const {operations,errors}=await setup(page,'receptionist');await page.goto('/recepcao/index.html');await page.getByRole('button',{name:'Pacientes e check-in'}).click();await page.getByLabel('Paciente',{exact:true}).selectOption(patient);await page.getByLabel('Fila / especialidade').selectOption(queue);await page.getByRole('button',{name:'Emitir senha',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('dialog').getByLabel('Link de acompanhamento')).toHaveValue(new RegExp('/acompanhar.html#'+token));expect(operations.find(o=>o.action==='checkin').priority).toBe(false);expect(errors).toEqual([]);});
test('doctor calls, starts and finishes the current ticket',async({page})=>{const {operations,errors}=await setup(page,'doctor');await page.goto('/medico/index.html');await page.getByLabel('Sua fila').selectOption(queue);await page.getByRole('button',{name:'Chamar próximo',exact:true}).click();await page.getByRole('button',{name:'Iniciar',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Confirmar',exact:true}).click();await page.getByRole('button',{name:'Finalizar',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Confirmar',exact:true}).click();await expect(page.getByText('Finalizado',{exact:true})).toBeVisible();expect(operations.map(o=>o.action)).toEqual(['call','start','finish']);expect(errors).toEqual([]);});
test('admin creates an email-bound invite and sees configuration and reports',async({page})=>{const {operations,errors}=await setup(page,'admin');await page.goto('/admin/index.html');await page.getByRole('button',{name:'Equipe e convites'}).click();await page.getByLabel('E-mail da pessoa').fill('doctor@example.test');await page.getByLabel('Função',{exact:true}).selectOption('doctor');await page.getByRole('button',{name:'Gerar convite'}).click();await expect(page.getByRole('dialog').getByLabel('Link do convite')).toHaveValue(new RegExp('/convite.html#'+token));await page.getByRole('dialog').getByRole('button',{name:'Fechar',exact:true}).click();await page.getByRole('button',{name:'Clínica e filas'}).click();await expect(page.getByRole('heading',{name:'Configurar fila de atendimento'})).toBeVisible();await page.getByRole('button',{name:'Relatórios'}).click();await expect(page.getByRole('button',{name:'Exportar resumo CSV'})).toBeVisible();expect(operations[0].email).toBe('doctor@example.test');expect(errors).toEqual([]);});
test('patient only sees their own tickets and has no clinical actions',async({page})=>{const {errors}=await setup(page,'patient');await page.goto('/paciente/index.html');await expect(page.getByRole('heading',{name:'Minhas senhas',exact:true})).toBeVisible();await expect(page.getByText('Posição: 1 · Estimativa: 15 min')).toBeVisible();await expect(page.getByRole('button',{name:'Iniciar',exact:true})).toHaveCount(0);await expect(page.getByText('TEST Patient',{exact:true})).toHaveCount(0);expect(errors).toEqual([]);});
test('public tracking works without login and hides token from URL',async({page})=>{const {errors}=await setup(page,'patient',{authenticated:false});await page.goto('/acompanhar.html#'+token);await expect(page.getByRole('heading',{name:'Dirija-se ao consultório TEST Room'})).toBeVisible();await expect(page).toHaveURL(/acompanhar.html$/);await expect(page.getByText('TEST Patient',{exact:true})).toHaveCount(0);expect(errors).toEqual([]);});
test('invite survives login and is accepted before entering the clinic',async({page})=>{const {errors}=await setup(page,'doctor');await page.goto('/convite.html#'+token);await page.getByRole('button',{name:'Aceitar convite',exact:true}).click();await expect(page).toHaveURL(/medico\/index.html/);expect(await page.evaluate(()=>sessionStorage.getItem('medflow.invite'))).toBeNull();expect(errors).toEqual([]);});
test('mobile reception layout remains within the viewport',async({page})=>{await page.setViewportSize({width:390,height:844});const {errors}=await setup(page,'receptionist');await page.goto('/recepcao/index.html');await expect(page.getByRole('heading',{name:'TEST Clinic'})).toBeVisible();const overflows=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);expect(overflows).toBe(false);expect(errors).toEqual([]);});
