import {api} from './api.js';
import {config} from './config.js';
import {session,logout,callback} from './auth.js';
import {homeFor,roleRoutes} from './navigation.js';
const page=document.body.dataset.page;
const statuses={waiting:'Aguardando',called:'Chamado',in_service:'Em atendimento',completed:'Finalizado',absent:'Ausente',cancelled:'Cancelado',open:'Aberta',closed:'Fechada'};
const roles={admin:'Administrador',doctor:'Médico',receptionist:'Recepcionista',patient:'Paciente'};
const message=document.querySelector('#message');
const content=document.querySelector('#workspace-content');
let me,clinic,data,tab='overview',busy=false,polling=false;
let timer,previousStatus;
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function tell(text,error=false){message.textContent=text;message.className=error?'notice error':'notice';}
function link(text,href){const a=el('a',text);a.href=href;return a;}
function button(text,fn,secondary=false){const b=el('button',text,secondary?'secondary':'');b.type='button';b.onclick=fn;return b;}
function panel(title){const section=el('section',undefined,'panel');section.append(el('h2',title));return section;}
function field(form,label,name,type='text',options={}){const wrap=el('label',label);const input=el(type==='select'?'select':'input');input.name=name;input.setAttribute('aria-label',label);if(type!=='select')input.type=type;Object.assign(input,options);wrap.append(input);form.append(wrap);return input;}
function select(form,label,name,items,display,key='id'){const node=field(form,label,name,'select',{required:true});const empty=el('option','Selecione…');empty.value='';node.append(empty);for(const item of items){const option=el('option',display(item));option.value=item[key];node.append(option);}return node;}
function form(section,action,label='Salvar',transform=values=>values){const f=el('form');f.dataset.action=action;section.append(f);const save=el('button',label);save.type='submit';f.onsubmit=async event=>{event.preventDefault();if(busy)return;busy=true;save.disabled=true;tell('Salvando…');try{const values=transform(Object.fromEntries(new FormData(f)));const result=await operate(action,values);f.reset();await load(true);tell('Operação concluída.');if(result.token)showToken(action==='invite'?'Convite criado':'Senha emitida',result.token,action==='invite',result.number);}catch(error){tell(error.message,true);}finally{busy=false;save.disabled=false;}};f.finish=()=>f.append(save);return f;}
async function operate(action,values={}){return api(`/clinics/${clinic}/actions`,{action,...values});}
function table(section,headers,rows,id){const wrap=el('div',undefined,'table-wrap');const t=el('table');if(id)t.id=id;const head=el('thead');const tr=el('tr');for(const h of headers){const th=el('th',h);th.scope='col';tr.append(th);}head.append(tr);const body=el('tbody');for(const row of rows){const tr=el('tr');for(const value of row){const td=el('td');if(value instanceof Node)td.append(value);else td.textContent=value??'—';tr.append(td);}body.append(tr);}if(!rows.length){const tr=el('tr');const td=el('td','Nenhum registro disponível.');td.colSpan=headers.length;tr.append(td);body.append(tr);}t.append(head,body);wrap.append(t);section.append(wrap);return t;}
function actions(...buttons){const div=el('div',undefined,'action-group');div.append(...buttons);return div;}
function closeDialog(){document.querySelector('#output-dialog').close();}
function confirmAction(title,fn){const dialog=document.querySelector('#output-dialog');dialog.replaceChildren(el('h2',title));const err=el('p',undefined,'error');err.setAttribute('role','alert');const yes=button('Confirmar',async()=>{yes.disabled=true;try{await fn();closeDialog();await load(true);tell('Operação concluída.');}catch(error){err.textContent=error.message;}finally{yes.disabled=false;}});dialog.append(err,actions(yes,button('Cancelar',closeDialog,true)));dialog.showModal();}
function editRecord(title,action,record){
 const dialog=document.querySelector('#output-dialog');dialog.replaceChildren(el('h2',title));const f=el('form');dialog.append(f);const name=field(f,'Nome','name','text',{required:true,minLength:2,maxLength:120,value:record.name});
 if(action==='queue_edit'){const rooms=select(f,'Consultório','room_id',data.rooms,r=>r.name);rooms.value=record.room_id;field(f,'Duração esperada (minutos)','expected_minutes','number',{required:true,min:1,max:240,value:record.expected_minutes});}
 const error=el('p',undefined,'error');error.setAttribute('role','alert');const save=el('button','Salvar');save.type='submit';f.append(error,save,button('Cancelar',closeDialog,true));f.onsubmit=async event=>{event.preventDefault();save.disabled=true;try{const values=Object.fromEntries(new FormData(f));if(action==='queue_edit')values.expected_minutes=Number(values.expected_minutes);await operate(action,{...values,id:record.id});closeDialog();await load(true);tell('Registro atualizado.');}catch(e){error.textContent=e.message;}finally{save.disabled=false;}};dialog.showModal();
}
function showToken(title,token,invite,number){const dialog=document.querySelector('#output-dialog');dialog.replaceChildren(el('h2',title));if(number)dialog.append(el('p',`Senha ${String(number).padStart(3,'0')}`,'ticket-number'));dialog.append(el('p',invite?'Compartilhe este link com a pessoa convidada. Ela deve cadastrar e confirmar o mesmo e-mail e aceitar o convite. Validade: 7 dias.':'Entregue este link apenas ao paciente. Não exige login, expira em 48 horas e mostra somente sua senha. Gerar outro link invalida o anterior.','muted'));
 const url=location.origin+(invite?'/convite.html#':'/acompanhar.html#')+token;
 const box=el('input');box.value=url;box.readOnly=true;box.setAttribute('aria-label',invite?'Link do convite':'Link de acompanhamento');dialog.append(box);
 const status=el('p');status.setAttribute('role','status');dialog.append(status,actions(button('Copiar link',async()=>{try{await navigator.clipboard.writeText(url);status.textContent='Link copiado.';}catch{box.select();status.textContent='Selecione e copie o link manualmente.';}}),button('Abrir',()=>window.open(url,'_blank','noopener'),true),button('Fechar',closeDialog,true)));dialog.showModal();
}
function liveTickets(){return (data.tickets||[]).filter(t=>['waiting','called','in_service'].includes(t.status));}
function ticketRows(tickets){return tickets.map(t=>{const buttons=[];if(['admin','receptionist'].includes(data.role)&&['waiting','called'].includes(t.status)){buttons.push(button('Cancelar',()=>confirmAction(`Cancelar a senha ${t.number}?`,()=>operate('cancel',{id:t.id})),true));buttons.push(button('Link paciente',async()=>{try{const result=await operate('tracking',{id:t.id});showToken('Acompanhar senha',result.token,false,t.number);}catch(e){tell(e.message,true);}},true));}
 if(data.role==='doctor'&&t.status==='called'){buttons.push(button('Iniciar',()=>confirmAction(`Iniciar atendimento da senha ${t.number}?`,()=>operate('start',{id:t.id}))));buttons.push(button('Ausente',()=>confirmAction(`Registrar ausência da senha ${t.number}?`,()=>operate('absent',{id:t.id})),true));}
 if(data.role==='doctor'&&t.status==='in_service')buttons.push(button('Finalizar',()=>confirmAction(`Finalizar atendimento da senha ${t.number}?`,()=>operate('finish',{id:t.id}))));
 return [String(t.number).padStart(3,'0'),t.patient_name,t.queue_name,t.priority?'Prioritário':'Regular',statuses[t.status],t.room||'—',actions(...buttons)];});}
function renderLive(){const target=document.querySelector('#live-panel');if(target){target.replaceChildren(el('h2','Fila em andamento'));table(target,['Senha','Paciente','Fila','Prioridade','Situação','Consultório','Ações'],ticketRows(liveTickets()));}
 const metrics=document.querySelector('#live-metrics');if(metrics){metrics.replaceChildren();for(const [key,title]of [['waiting','Aguardando'],['called','Chamados'],['in_service','Em atendimento']]){const c=el('article',undefined,'card');c.append(el('span',title),el('strong',String((data.tickets||[]).filter(t=>t.status===key).length)));metrics.append(c);}}
 const own=document.querySelector('#own-tickets');if(own)renderOwn(own);
}
function renderOwn(target){target.replaceChildren();if(!data.tickets.length){target.append(el('p','Você ainda não tem senhas vinculadas a esta conta. A recepção pode emitir uma senha e fornecer um link individual.','muted'));return;}for(const t of data.tickets){const c=panel(`${t.clinic} · ${t.queue}`);c.append(el('p',String(t.number).padStart(3,'0'),'ticket-number'),el('p',statuses[t.status],'badge'),el('p',t.status==='waiting'?`Posição: ${t.position} · Estimativa: ${t.estimated_minutes} min`:`Consultório: ${t.room||'A definir'}`));target.append(c);}}
function render(){content.replaceChildren();if(!data)return;
 const intro=el('div',undefined,'page-heading');intro.append(el('p',roles[data.role],'eyebrow'),el('h1',data.clinic?.name||'Minhas senhas'),el('p','Atualização automática a cada 10 segundos.','muted'));content.append(intro);
 if(data.role==='patient'){const own=el('div');own.id='own-tickets';content.append(own);renderOwn(own);return;}
 if(tab==='overview'){
  const metrics=el('div',undefined,'cards');metrics.id='live-metrics';content.append(metrics);
  if(data.role==='doctor'){
   const section=panel('Chamar próximo paciente');const f=form(section,'call','Chamar próximo');select(f,'Sua fila','queue_id',data.queues.filter(q=>q.status==='open'),q=>`${q.name} · ${q.room_name||'Consultório não definido'}`);f.finish();content.append(section);
  }
  const live=panel('Fila em andamento');live.id='live-panel';content.append(live);
  const history=panel('Histórico recente · 48 horas');table(history,['Senha','Paciente','Fila','Prioridade','Situação','Consultório','Ações'],ticketRows(data.tickets.filter(t=>!['waiting','called','in_service'].includes(t.status))));content.append(history);renderLive();
 }
 if(tab==='reception'){
  const grid=el('div',undefined,'form-grid');const section=panel('Cadastrar paciente');const f=form(section,'patient','Cadastrar paciente');field(f,'Nome do paciente','name','text',{required:true,minLength:2,maxLength:120});field(f,'E-mail da conta do paciente (opcional)','email','email',{maxLength:254});f.append(el('p','Se o paciente já tiver uma conta confirmada com este e-mail, poderá acompanhar suas senhas ao entrar. O link individual funciona sem conta.','muted'));f.finish();grid.append(section);
  const check=panel('Registrar chegada e emitir senha');const c=form(check,'checkin','Emitir senha',values=>({...values,priority:values.priority==='on'}));select(c,'Paciente','patient_id',data.patients,p=>`${p.name} · ${p.id.slice(0,8)}`);select(c,'Fila / especialidade','queue_id',data.queues.filter(q=>q.status==='open'),q=>`${q.name} · ${q.specialty_name} · ${q.doctor_name||'Médico'}`);field(c,'Atendimento prioritário','priority','checkbox');c.finish();grid.append(check);content.append(grid);
  const list=panel('Pacientes cadastrados · até 500 mais recentes');table(list,['Nome','Código','Conta vinculada','Ações'],data.patients.map(p=>[p.name,p.id.slice(0,8),p.user_id?'Sim':'Não',button('Corrigir nome',()=>editRecord('Editar paciente','patient_edit',p),true)]));content.append(list);
  const live=panel('Fila em andamento');live.id='live-panel';content.append(live);renderLive();
 }
 if(tab==='settings'){
  const s=panel('Configurações da clínica');const f=form(s,'settings');field(f,'Nome','name','text',{required:true,minLength:3,maxLength:120,value:data.clinic.name});field(f,'E-mail de contato','contact_email','email',{required:true,value:data.clinic.contact_email||me.email});field(f,'Cidade','city','text',{required:true,minLength:2,maxLength:120,value:data.clinic.city||''});field(f,'Fuso horário','timezone','text',{required:true,value:data.clinic.timezone});f.finish();content.append(s);
  const grid=el('div',undefined,'form-grid');for(const [action,title,items]of [['specialty','Especialidades',data.specialties],['room','Consultórios',data.rooms]]){const section=panel(title);const f=form(section,action,'Adicionar');field(f,'Nome','name','text',{required:true,minLength:2,maxLength:120});f.finish();table(section,['Nome','Ações'],items.map(i=>[i.name,button('Editar',()=>editRecord('Editar registro',action+'_edit',i),true)]));grid.append(section);}content.append(grid);
  const queues=panel('Configurar fila de atendimento');const q=form(queues,'queue','Criar fila',values=>({...values,expected_minutes:Number(values.expected_minutes)}));field(q,'Nome da fila','name','text',{required:true,minLength:2,maxLength:120});select(q,'Especialidade','specialty_id',data.specialties,s=>s.name);select(q,'Consultório','room_id',data.rooms,r=>r.name);select(q,'Médico','doctor_id',data.members.filter(m=>m.role==='doctor'&&m.active),m=>m.name||m.user_id.slice(0,8),'user_id');field(q,'Duração estimada por atendimento (minutos)','expected_minutes','number',{required:true,min:1,max:240,value:15});q.finish();table(queues,['Fila','Médico','Consultório','Situação','Ações'],data.queues.map(q=>[q.name,q.doctor_name,q.room_name,statuses[q.status],actions(button('Editar',()=>editRecord('Editar fila','queue_edit',q),true),button(q.status==='open'?'Fechar fila':'Abrir fila',()=>confirmAction(`${q.status==='open'?'Fechar':'Abrir'} a fila ${q.name}?`,()=>operate('queue_status',{id:q.id,status:q.status==='open'?'closed':'open'})),true))]));content.append(queues);
 }
 if(tab==='team'){
  const s=panel('Convidar integrante');const f=form(s,'invite','Gerar convite');field(f,'E-mail da pessoa','email','email',{required:true,maxLength:254});select(f,'Função','role',Object.entries(roles).map(([id,name])=>({id,name})),r=>r.name);f.finish();s.append(el('p','O convite não envia e-mail automaticamente. Copie o link e compartilhe com a pessoa. Ela deve aceitar com o e-mail informado.','muted'));content.append(s);
  const members=panel('Equipe e vínculos');table(members,['Nome','Função','Situação','Alterar função','Ações'],data.members.map(m=>{const selectRole=el('select');selectRole.setAttribute('aria-label',`Função de ${m.name||m.user_id}`);for(const[id,label]of Object.entries(roles)){const o=el('option',label);o.value=id;selectRole.append(o);}selectRole.value=m.role;return[m.name||m.user_id.slice(0,8),roles[m.role],m.active?'Ativo':'Desativado',selectRole,actions(button('Salvar função',()=>confirmAction(`Alterar a função de ${m.name||'integrante'}?`,()=>operate('member',{user_id:m.user_id,role:selectRole.value,active:m.active}))),button(m.active?'Desativar':'Reativar',()=>confirmAction(`${m.active?'Desativar':'Reativar'} este vínculo?`,()=>operate('member',{user_id:m.user_id,role:m.role,active:!m.active})),true))];}));content.append(members);
  const invites=panel('Convites');table(invites,['E-mail','Função','Situação','Validade','Ações'],data.invites.map(i=>[i.email,roles[i.role],i.accepted_at?'Aceito':i.revoked_at?'Revogado':new Date(i.expires_at)<new Date()?'Expirado':'Pendente',new Date(i.expires_at).toLocaleString('pt-BR'),!i.accepted_at&&!i.revoked_at?button('Revogar',()=>confirmAction('Revogar este convite?',()=>operate('revoke_invite',{id:i.id})),true):'—']));content.append(invites);
 }
 if(tab==='reports'){
  const report=data.report||{};const section=panel('Atendimentos · últimos 30 dias');const metrics=[['total','Senhas emitidas'],['completed','Finalizados'],['cancelled','Cancelados'],['absent','Ausências'],['average_wait_minutes','Espera média (min)'],['average_service_minutes','Atendimento médio (min)']];table(section,['Indicador','Valor'],metrics.map(([k,t])=>[t,report[k]??'Sem amostra']));section.append(button('Exportar resumo CSV',()=>{const rows=[['Indicador','Valor'],...metrics.map(([k,t])=>[t,report[k]??''])];const csv='\ufeff'+rows.map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=link('Baixar',url);a.download='medflow-relatorio.csv';a.click();URL.revokeObjectURL(url);}));content.append(section);
 }
}
function navigation(){const nav=document.querySelector('#role-nav');nav.replaceChildren();const tabs=data.role==='admin'?[['overview','Visão geral'],['reception','Recepção'],['team','Equipe e convites'],['settings','Clínica e filas'],['reports','Relatórios']]:data.role==='receptionist'?[['overview','Filas'],['reception','Pacientes e check-in']]:[['overview',data.role==='doctor'?'Minha fila':'Minhas senhas']];if(!tabs.some(([key])=>key===tab))tab='overview';for(const[key,label]of tabs){const b=button(label,()=>{tab=key;navigation();render();},true);b.className=tab===key?'nav-button active':'nav-button';nav.append(b);}nav.append(link('Aceitar convite','/convite.html'),link('Minhas solicitações','/solicitacao.html'));if(me.platform_admin)nav.append(link('Administrar plataforma','/superadmin/index.html'));}
async function load(full=false){if(!clinic||polling)return;polling=true;try{data=await api(`/clinics/${clinic}/workspace`);if(full){navigation();render();}else renderLive();document.querySelector('#connection').textContent=`Atualizado às ${new Date().toLocaleTimeString('pt-BR')}`;}finally{polling=false;}}
async function workspace(){
 if(!session()){location.replace('/login.html');return;}
 me=await api('/me');document.querySelector('#identity').textContent=me.email;
 const memberships=me.memberships.filter(m=>m.clinics?.status==='active');const select=document.querySelector('#clinic-select');
 for(const m of memberships){const o=el('option',`${m.clinics.name} · ${roles[m.role]}`);o.value=m.clinic_id;select.append(o);}
 if(!memberships.length){content.append(el('h1','Vamos preparar seu acesso'),el('p','Você ainda não possui vínculo com uma clínica ativa. Envie uma solicitação ou aceite o convite da sua equipe.','muted'),link('Solicitar clínica','/solicitacao.html'),el('p'),link('Aceitar convite','/convite.html'));return;}
 clinic=sessionStorage.getItem('medflow.clinic');if(!memberships.some(m=>m.clinic_id===clinic))clinic=memberships[0].clinic_id;select.value=clinic;
 select.onchange=async()=>{clinic=select.value;sessionStorage.setItem('medflow.clinic',clinic);tab='overview';try{await load(true);}catch(error){tell(error.message,true);}};
 await load(true);tell('');timer=setInterval(()=>{if(!document.hidden&&!busy)load(false).catch(error=>tell(error.message,true));},10000);
}
function rememberedToken(storageKey){const hash=location.hash.slice(1);if(/^[a-f0-9]{64}$/.test(hash)){sessionStorage.setItem(storageKey,hash);history.replaceState(null,'',location.pathname);}return sessionStorage.getItem(storageKey);}
async function track(){
 const token=rememberedToken('medflow.tracking');const f=document.querySelector('#track-form');
 f.onsubmit=event=>{event.preventDefault();const input=f.elements.token.value.trim();if(!/^[a-f0-9]{64}$/.test(input)){tell('Informe o código de 64 caracteres recebido da recepção.',true);return;}sessionStorage.setItem('medflow.tracking',input);location.reload();};
 document.querySelector('#notifications').onclick=async()=>{if(!('Notification'in window)){tell('Seu navegador não oferece notificações.');return;}const status=await Notification.requestPermission();tell(status==='granted'?'Alertas ativados enquanto esta página estiver aberta.':'Permissão de notificações não concedida.');};
 if(!token){tell('Abra o link individual entregue pela recepção ou informe seu código.');return;}
 async function update(){const response=await fetch(config.apiUrl+'/public/track',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})});const result=await response.json();if(!response.ok)throw new Error(result.error?.message||'Código indisponível.');const t=result.data;document.querySelector('#tracking-result').replaceChildren();const section=panel(t.clinic);section.append(el('p',t.queue,'muted'),el('p',String(t.number).padStart(3,'0'),'ticket-number'),el('p',statuses[t.status],'badge'),el('h2',t.status==='waiting'?`Você está na posição ${t.position}`:t.status==='called'?`Dirija-se ao consultório ${t.room||'informado pela equipe'}`:t.status==='in_service'?'Seu atendimento está em andamento':statuses[t.status]),el('p',t.status==='waiting'?`Estimativa de espera: ${t.estimated_minutes} minutos. O tempo pode variar conforme os atendimentos e prioridades.`:`Consultório: ${t.room||'—'}`,'muted'));document.querySelector('#tracking-result').append(section);if(t.status==='called'&&previousStatus&&previousStatus!==t.status&&'Notification'in window&&Notification.permission==='granted')new Notification('MedFlow: sua senha foi chamada',{body:`Senha ${t.number} · Consultório ${t.room||'a confirmar'}`});previousStatus=t.status;tell(`Atualizado às ${new Date().toLocaleTimeString('pt-BR')}`);if(['completed','absent','cancelled'].includes(t.status))clearInterval(timer);}
 await update();if(!['completed','absent','cancelled'].includes(previousStatus))timer=setInterval(()=>{if(!document.hidden)update().catch(error=>tell(error.message,true));},10000);
}
async function invite(){
 let token=rememberedToken('medflow.invite');const f=document.querySelector('#invite-form');if(token)f.elements.token.value=token;
 if(!session()){tell('Entre ou cadastre sua conta, confirme o e-mail e volte a este convite.');document.querySelector('#invite-auth').hidden=false;}
 f.onsubmit=async event=>{event.preventDefault();token=f.elements.token.value.trim();sessionStorage.setItem('medflow.invite',token);if(!session()){location.assign('/login.html');return;}const b=f.querySelector('button');b.disabled=true;try{const id=await api('/invites/accept',{token});sessionStorage.removeItem('medflow.invite');sessionStorage.setItem('medflow.clinic',id);me=await api('/me');location.assign(homeFor(me));}catch(error){tell(error.message,true);}finally{b.disabled=false;}};
}
async function start(){await callback();document.querySelector('#logout')?.addEventListener('click',()=>logout().catch(error=>tell(error.message,true)));if(page==='workspace')await workspace();else if(page==='track')await track();else if(page==='invite')await invite();}
window.addEventListener('pagehide',()=>clearInterval(timer));
start().catch(error=>tell(error.message||'Não foi possível conectar. Confira se os servidores estão ativos.',true));
