begin;
create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated;
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text not null default '' check(length(display_name)<=120), created_at timestamptz not null default now());
create table public.platform_admins (user_id uuid primary key references auth.users(id), created_at timestamptz not null default now());
create table public.clinics (id uuid primary key default gen_random_uuid(), name text not null check(length(trim(name)) between 3 and 120), status text not null default 'active' check(status in ('pending','active','rejected','suspended')), created_at timestamptz not null default now());
create table public.clinic_requests (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id), name text not null check(length(trim(name)) between 3 and 120), contact_email text not null check(length(contact_email)<=254 and contact_email ~ '^[^ @]+@[^ @]+\.[^ @]+$'), city text not null check(length(trim(city)) between 2 and 120), status text not null default 'pending' check(status in ('pending','active','rejected')), clinic_id uuid references public.clinics(id), reason text, decided_by uuid references auth.users(id), decided_at timestamptz, created_at timestamptz not null default now(), check ((status='pending' and clinic_id is null and reason is null and decided_by is null and decided_at is null) or (status='active' and clinic_id is not null and decided_by is not null and decided_at is not null and reason is null) or (status='rejected' and clinic_id is null and length(trim(reason)) between 5 and 500 and decided_by is not null and decided_at is not null)));
create unique index one_pending_request on public.clinic_requests(owner_id) where status='pending';
create index clinic_requests_status_created on public.clinic_requests(status,created_at);
create table public.clinic_members (clinic_id uuid not null references public.clinics(id), user_id uuid not null references auth.users(id), role text not null check(role in ('admin','doctor','receptionist','patient')), created_at timestamptz not null default now(), primary key(clinic_id,user_id));
create index members_user_clinic on public.clinic_members(user_id,clinic_id);
create table public.patients (id uuid primary key default gen_random_uuid(), clinic_id uuid not null references public.clinics(id), user_id uuid references auth.users(id), name text not null check(length(name) between 2 and 120), created_at timestamptz not null default now(), unique(clinic_id,id));
create table public.specialties (id uuid primary key default gen_random_uuid(), clinic_id uuid not null references public.clinics(id), name text not null, created_at timestamptz not null default now(), unique(clinic_id,id), unique(clinic_id,name));
create table public.rooms (id uuid primary key default gen_random_uuid(), clinic_id uuid not null references public.clinics(id), name text not null, created_at timestamptz not null default now(), unique(clinic_id,id), unique(clinic_id,name));
create table public.queues (id uuid primary key default gen_random_uuid(), clinic_id uuid not null references public.clinics(id), specialty_id uuid not null, doctor_id uuid, status text not null default 'open' check(status in ('open','closed')), created_at timestamptz not null default now(), unique(clinic_id,id), foreign key(clinic_id,specialty_id) references public.specialties(clinic_id,id), foreign key(clinic_id,doctor_id) references public.clinic_members(clinic_id,user_id));
create table public.queue_tickets (id uuid primary key default gen_random_uuid(), clinic_id uuid not null references public.clinics(id), queue_id uuid not null, patient_id uuid not null, room_id uuid, number integer not null check(number>0), ticket_date date not null default current_date, status text not null default 'waiting' check(status in ('waiting','called','in_service','completed','absent','cancelled')), created_at timestamptz not null default now(), called_at timestamptz, unique(clinic_id,id), unique(clinic_id,queue_id,ticket_date,number), foreign key(clinic_id,queue_id) references public.queues(clinic_id,id), foreign key(clinic_id,patient_id) references public.patients(clinic_id,id), foreign key(clinic_id,room_id) references public.rooms(clinic_id,id));
create table public.appointments (id uuid primary key default gen_random_uuid(), clinic_id uuid not null references public.clinics(id), ticket_id uuid not null, doctor_id uuid not null, started_at timestamptz not null default now(), ended_at timestamptz, status text not null default 'in_service' check(status in ('in_service','completed')), unique(clinic_id,ticket_id), check(ended_at is null or ended_at>=started_at), foreign key(clinic_id,ticket_id) references public.queue_tickets(clinic_id,id), foreign key(clinic_id,doctor_id) references public.clinic_members(clinic_id,user_id));
create table public.audit_logs (id uuid primary key default gen_random_uuid(), clinic_id uuid references public.clinics(id), actor_id uuid not null references auth.users(id), action text not null, target_id uuid not null, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create index audit_clinic_created on public.audit_logs(clinic_id,created_at desc);
create index tickets_queue_status on public.queue_tickets(clinic_id,queue_id,status,created_at);
create index patients_user on public.patients(user_id);
create function private.is_platform_admin() returns boolean language sql stable security definer set search_path='' as $$ select auth.uid() is not null and exists(select 1 from public.platform_admins where user_id=auth.uid()) $$;
create function private.has_clinic_role(p_clinic uuid,p_roles text[]) returns boolean language sql stable security definer set search_path='' as $$ select auth.uid() is not null and exists(select 1 from public.clinic_members m join public.clinics c on c.id=m.clinic_id where m.user_id=auth.uid() and m.clinic_id=p_clinic and m.role=any(p_roles) and c.status='active') $$;
revoke all on function private.is_platform_admin(), private.has_clinic_role(uuid,text[]) from public,anon;
grant execute on function private.is_platform_admin(), private.has_clinic_role(uuid,text[]) to authenticated;
create function private.new_profile() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.profiles(id,display_name) values(new.id,left(coalesce(new.raw_user_meta_data->>'display_name',''),120)); return new; end $$;
revoke all on function private.new_profile() from public,anon,authenticated;
create trigger auth_profile after insert on auth.users for each row execute function private.new_profile();
alter table public.profiles enable row level security;
revoke all on public.profiles from anon,authenticated;
grant select on public.profiles to authenticated;
alter table public.platform_admins enable row level security;
revoke all on public.platform_admins from anon,authenticated;
grant select on public.platform_admins to authenticated;
alter table public.clinics enable row level security;
revoke all on public.clinics from anon,authenticated;
grant select on public.clinics to authenticated;
alter table public.clinic_requests enable row level security;
revoke all on public.clinic_requests from anon,authenticated;
grant select on public.clinic_requests to authenticated;
alter table public.clinic_members enable row level security;
revoke all on public.clinic_members from anon,authenticated;
grant select on public.clinic_members to authenticated;
alter table public.patients enable row level security;
revoke all on public.patients from anon,authenticated;
grant select on public.patients to authenticated;
alter table public.specialties enable row level security;
revoke all on public.specialties from anon,authenticated;
grant select on public.specialties to authenticated;
alter table public.rooms enable row level security;
revoke all on public.rooms from anon,authenticated;
grant select on public.rooms to authenticated;
alter table public.queues enable row level security;
revoke all on public.queues from anon,authenticated;
grant select on public.queues to authenticated;
alter table public.queue_tickets enable row level security;
revoke all on public.queue_tickets from anon,authenticated;
grant select on public.queue_tickets to authenticated;
alter table public.appointments enable row level security;
revoke all on public.appointments from anon,authenticated;
grant select on public.appointments to authenticated;
alter table public.audit_logs enable row level security;
revoke all on public.audit_logs from anon,authenticated;
grant select on public.audit_logs to authenticated;

create policy own_profile on public.profiles for select to authenticated using(id=(select auth.uid()));
create policy own_platform_role on public.platform_admins for select to authenticated using(user_id=(select auth.uid()));
create policy clinic_visibility on public.clinics for select to authenticated using(private.is_platform_admin() or private.has_clinic_role(id,array['admin','doctor','receptionist','patient']));
create policy request_visibility on public.clinic_requests for select to authenticated using(owner_id=(select auth.uid()) or private.is_platform_admin());
create policy membership_visibility on public.clinic_members for select to authenticated using(user_id=(select auth.uid()) or private.has_clinic_role(clinic_id,array['admin']));
create policy patient_visibility on public.patients for select to authenticated using(private.has_clinic_role(clinic_id,array['admin','doctor','receptionist']) or (user_id=(select auth.uid()) and private.has_clinic_role(clinic_id,array['patient'])));
create policy specialty_visibility on public.specialties for select to authenticated using(private.has_clinic_role(clinic_id,array['admin','doctor','receptionist']));
create policy room_visibility on public.rooms for select to authenticated using(private.has_clinic_role(clinic_id,array['admin','doctor','receptionist']));
create policy queue_visibility on public.queues for select to authenticated using(private.has_clinic_role(clinic_id,array['admin','receptionist']) or (doctor_id=(select auth.uid()) and private.has_clinic_role(clinic_id,array['doctor'])));
create policy ticket_visibility on public.queue_tickets for select to authenticated using(private.has_clinic_role(clinic_id,array['admin','receptionist']) or (private.has_clinic_role(clinic_id,array['doctor']) and exists(select 1 from public.queues q where q.clinic_id=queue_tickets.clinic_id and q.id=queue_tickets.queue_id and q.doctor_id=(select auth.uid()))));
create policy appointment_visibility on public.appointments for select to authenticated using(private.has_clinic_role(clinic_id,array['admin']) or (doctor_id=(select auth.uid()) and private.has_clinic_role(clinic_id,array['doctor'])));
create policy audit_visibility on public.audit_logs for select to authenticated using((clinic_id is null and private.is_platform_admin()) or (clinic_id is not null and private.has_clinic_role(clinic_id,array['admin'])));
-- Definer implementations live in a non-exposed schema; invoker wrappers are the REST contract.
create function private.submit_clinic_request(p_name text,p_contact_email text,p_city text) returns uuid language plpgsql security definer set search_path='' as $$
declare v_id uuid; begin
 if auth.uid() is null or not exists(select 1 from auth.users where id=auth.uid() and email_confirmed_at is not null and not is_anonymous) then raise insufficient_privilege; end if;
 insert into public.clinic_requests(owner_id,name,contact_email,city) values(auth.uid(),trim(p_name),trim(p_contact_email),trim(p_city)) returning id into v_id;
 insert into public.audit_logs(actor_id,action,target_id) values(auth.uid(),'clinic_request.submitted',v_id);
 return v_id;
end $$;
create function private.decide_clinic_request(p_request_id uuid,p_decision text,p_reason text default null) returns uuid language plpgsql security definer set search_path='' as $$
declare v_request public.clinic_requests; v_clinic uuid; begin
 if not private.is_platform_admin() then raise insufficient_privilege; end if;
 select * into v_request from public.clinic_requests where id=p_request_id for update;
 if not found or v_request.status<>'pending' then raise exception 'Request is not pending'; end if;
 if p_decision='approve' then
  insert into public.clinics(name) values(v_request.name) returning id into v_clinic;
  insert into public.clinic_members(clinic_id,user_id,role) values(v_clinic,v_request.owner_id,'admin');
  update public.clinic_requests set status='active',clinic_id=v_clinic,decided_by=auth.uid(),decided_at=now() where id=p_request_id;
 elsif p_decision='reject' and length(trim(p_reason)) between 5 and 500 then
  update public.clinic_requests set status='rejected',reason=trim(p_reason),decided_by=auth.uid(),decided_at=now() where id=p_request_id;
 else raise exception 'Invalid decision'; end if;
 insert into public.audit_logs(actor_id,action,target_id,metadata) values(auth.uid(),'clinic_request.'||p_decision,p_request_id,jsonb_build_object('clinic_id',v_clinic));
 return coalesce(v_clinic,p_request_id);
end $$;
create function public.submit_clinic_request(p_name text,p_contact_email text,p_city text) returns uuid language sql security invoker set search_path='' as $$ select private.submit_clinic_request(p_name,p_contact_email,p_city) $$;
create function public.decide_clinic_request(p_request_id uuid,p_decision text,p_reason text default null) returns uuid language sql security invoker set search_path='' as $$ select private.decide_clinic_request(p_request_id,p_decision,p_reason) $$;
revoke all on function private.submit_clinic_request(text,text,text),private.decide_clinic_request(uuid,text,text),public.submit_clinic_request(text,text,text),public.decide_clinic_request(uuid,text,text) from public,anon;
grant execute on function private.submit_clinic_request(text,text,text),private.decide_clinic_request(uuid,text,text),public.submit_clinic_request(text,text,text),public.decide_clinic_request(uuid,text,text) to authenticated;
commit;
